name: 'Snowplow GitHub Action'
description: 'Sends events to a Snowplow collector'
author: 'Paul Boocock'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  pre: 'dist/pre/index.js'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
